### ISSUE TITLE
Initialize and Setup Tailwind CSS 

### ISSUE THREAD

**Issue by ardianta** [Loteng-Dev/lotengdev-web#2]
Install and Setup:
- npm init
- install Tailwind CSS
- tailwind init

Create:
- `public/index.html`
- `public/events.html`
- `public/speakers.html`
- `public/about.html`
- `src/main.css`
- `tailwind.config.js`
- `postcss.config.js`

Read the Tailwind Docs: https://tailwindcss.com/docs/installation

**Comment by vancassa** [comment]
Halo, boleh saya kerjakan ini?

**Comment by ardianta** [comment]
Hi @vancassa boleh, silahkan kirim PR

**Comment by ardianta** [comment]
Hi @vancassa  issue ini sudah dikerjakan di PR #12

**Comment by vancassa** [comment]
Oo maaf, saya kira tidak ada yg mengerjakan karena tidak ada assignee

**Comment by ahmadhabibi14** [comment]
@vancassa masih ada issue lain, mari kita kerjakan 💪
