### ISSUE TITLE
[Slicing] Halaman Home - Navbar

### ISSUE THREAD

**Issue by ardianta** [Loteng-Dev/lotengdev-web#3]
Dekstop:
![image](https://user-images.githubusercontent.com/4420029/197931152-11f46011-0731-41fb-9c8a-f672889a509e.png)
Mobile:
![image](https://user-images.githubusercontent.com/4420029/197931202-66db0adb-5196-4073-be5b-ff72b9d4dfa9.png)

*Note*: cuma slicing komponen navbar aja, untuk sidebar di mobile akan dibuat di issue terpisah

**Comment by vancassa** [comment]
Boleh saya kerjakan yg ini?

**Comment by ardianta** [comment]
@ahmadhabibi14 jadi ngerjain yang ini? Aku mau assign ke @vancassa
